branches:
  only:
  - master
  - "/[v]\\d\\.\\d\\.\\d/"
cache: pip
deploy:
  provider: pypi
  user: ShanHuang
  password:
    secure: AHb9dKqmLIXAMHiibBHkmMpzf4aUsBwgW745FUGX1w0dV5q2mBn967MlVKjxJPzGa5vtVIoGOy/Qj+J0i6RqrhbeP0S07zxQH+JeV1CufU0sHZ0LIA7DmH0htSH42SyL+ZmKa/O+FH76OWHAXkhO62hgAp3knfOUhHC6YTquyKba826R5ltK/3Yzwl1DFULr0orAAnV79xBjBRfRvl2YxA9ng8jE7p4QoUkLmnQZ7928JB1O7Q/lKVrZaL8HH1ejssTgeHfhldsOo7jrosALTrQxGlltvjb+NTiNRSH7c8yX4aIR2g5RunVWyb1OkxYiNKJKFH9C4sgKZaVDyfyvZ+BzZC7sS+fka8yRU/iR/EaS7/1V62VDUsnJvQqoBiJoFWVFvrv+EHmdA9perqNED8ENRwZf7EFKc/55XYNYj0ukWJy4TtgHylkA2/MPtMPRh1SfivwqwO/3+2ZLrAZf/LTDJyO0H01JdUAKpPKPNQE7V07yKhd+3CpTki8rF9i9R6FF1G5k/IDLOKD31o8AHXfo661NpxYzB39/9CILFG8q4vU2staFcmxCDNIQX+y6hnRQUqfntYnkKjkumq2/0pGKanZjZElw/8xnkx0JF+C/d6sf+uQ9zOn2Pxf8IcfYHdXOyCtQ8vYc3Yr5Pd/uEAcaoQ587IJnuyVzpcswyKE=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: zalando/expan
env:
- TOXENV=py
install:
- pip install tox coveralls
- pip install -r requirements_tox_test.txt
language: python
python:
- 2.7
- 3.6
script: tox
after_success:
- coveralls
